//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class process
    {
        public int ID { get; set; }
        public string ProcName { get; set; }
        public Nullable<int> ProcID { get; set; }
        public Nullable<System.DateTime> ProcTime { get; set; }
        public string CompName { get; set; }
        public string CompUser { get; set; }
        public string IP { get; set; }
    }
}
